apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hxzncztme-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hxzncztme-nodejs 
  name: hxzncztme-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hxzncztme-nodejs 
